### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-ws-api#30]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by cesarhernandezgt** [comment]
I view this issue on my inbox and proceed to create the Bugzilla ticket:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539531

**Comment by m0mus** [comment]
@cesarhernandezgt Thanks! I'll assign this issue to you then :)

**Comment by Tomas-Kraus** [comment]
Created https://jenkins.eclipse.org/jaxws/job/jax-ws-api-master-build/
Looks ike there is a problem with accessing GitHub via ssh:
`Fetching upstream changes from ssh://git@github.com/eclipse-ee4j/jax-ws-api
 > git --version # timeout=10
 > git fetch --tags --progress ssh://git@github.com/eclipse-ee4j/jax-ws-api +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress ssh://git@github.com/eclipse-ee4j/jax-ws-api +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.`
Changed GIT config to use HTTPS. This seems to work.

Build fails on
`Could not find artifact javax.xml.bind:jaxb-api:jar:2.3.1 in central (https://repo.maven.apache.org/maven2)`
This is OK because 2.3.1 was not released yet.

**Comment by Tomas-Kraus** [comment]
There already is Bugzilla request: https://bugs.eclipse.org/bugs/show_bug.cgi?id=538893
539531 was closed as duplicate.

**Comment by Tomas-Kraus** [comment]
Added https://jenkins.eclipse.org/jaxws/job/jax-ws-api-ee4j8-build/ for EE4J_8 branch.

**Comment by Tomas-Kraus** [comment]
Both jobs are working fine, closing this issue.
